### ISSUE TITLE
Cordova app becomes unresponsive when used with the Intercom Cordova plugin on Android  

### ISSUE THREAD

**Issue by beaudry12087** [smartlook/cordova-smartlook#10]
I have encountered an issue with the Smartlook Cordova plugin on Android with the [Intercom plugin](https://github.com/intercom/intercom-cordova). If the Smartlook recording is enabled and the Intercom messenger popup is displayed, 6 to 7 minutes after, the app becomes unresponsive. I see in Logcat logs like this one `fm.trebble I/Choreographer: Skipped 186 frames! The application may be doing too much work on its main thread.` The issue doesn't occur if I disable the Smartlook Screen recording on Android.

**Comment by SenNeonoveNoci** [comment]
Hi, @beaudry12087 if you remove Smartlook recording the `I/Choreographer` logs disappear?
Also is there any chance you can provide us with a demo app where we can try this issue?

**Comment by SenNeonoveNoci** [comment]
@beaudry12087 Is this issue still actual? We need some additional info from you to fix it.
