### ISSUE TITLE
Incompatibility with cordova-android@9.0.0

### ISSUE THREAD

**Issue by maxymczech** [smartlook/cordova-smartlook#18]
Hello. We were using `cordova-smartlook` in our application. After updating to latest `cordova-android@9.0.0`, Smartlook plugin causes the app to crash due to memory leak error. For the time being, we have removed smartlook from the app, but we would relly love to have it back. Can you please look into this?

P. S. If it helps, I can send you `adb logcat` logs from crashing app.

**Comment by SenNeonoveNoci** [comment]
Hi @maxymczech, I'm moving this issue to [smartlook-mobile-issue-tracker](https://github.com/smartlook/smartlook-mobile-issue-tracker).
