### ISSUE TITLE
Question: Can you use Smartlook on a React + Ionic (Capacitor) app ?

### ISSUE THREAD

**Issue by jcardenaslie** [smartlook/cordova-smartlook#36]
Can be this plugin be issued with a react + ionic (capacitor) app ?
I read this Doc: [https://mobile.developer.smartlook.com/v1.0/reference/ionic-sdk-installation]
But the example is with Angular. Can be used with react ?

thanks

**Comment by wsamoht** [comment]
I am using it with Vue so it should work with React as well.

**Comment by jcardenaslie** [comment]
Hey @wsamoht thanks for answering. 
Which SDK are you using?

Thanks :)

**Comment by jcardenaslie** [comment]
Thanks a lot @wsamoht !

Ill give it a try!

**Comment by jcardenaslie** [comment]
I think that `new SmartlookSetupConfig(YOUR_SMARTLOOK_KEY)` is working fine 'cuz im seeing this result on the Logcat from Android

`To native (Cordova plugin): callbackId: SmartlookPlugin781912788, service: SmartlookPlugin, action: setupAndStartRecording, actionArgs: [YOUR_SMARTLOOK_KEY,-1,"",false,false,[]]`

But not sure if `Smartlook.setupAndStartRecording()` is working, cuz nothing is reaching the smartlook recording dashboard

I consoled the return of the function, but not sure it actually return something
I/Capacitor/Console: File: http://localhost/static/js/main.c5b99d0e.js - Line 2 - Msg: INIT SMARTLOOK undefined

**Comment by wsamoht** [comment]
Hmmm...the `MPEG4Writer` logs seem normal so that is encouraging that it is working. The 429 error suggests rate limiting on Smartlook's end for their API. Maybe validate your Smartlook secret is correct and what is getting passed to `SmartlookSetupConfig` is the same/correct.

It also does take a little bit for Smartlook's dashboard to show you the recordings as they do some post-processing of the video too I believe.

**Comment by c0mtru1se** [comment]
Hi @jcardenaslie !
Just fyi, we have released a brand new, ground-up rewritten [version 2.0 of this plugin](https://github.com/smartlook/cordova-smartlook/releases/tag/v2.0.0) today. It uses our new, and long-term supported 2.x+ native SDKs.

We have also pushed a [PR](https://github.com/danielsogl/awesome-cordova-plugins/pull/4510) to the `awesome-cordova-plugins` repository. Once the PR gets merged and released, you should be able to use both those plugins in your Ionic project. `Capacitor` with both `React`, `Angular` and `Vue` frontends is also fully supported and tested by us internally.
Please then kindly consult our [docs](https://mobile.developer.smartlook.com/reference/cordova-sdk-integration) to migrate to the v2.0 as there were some breaking changes in the API. I'll gladly be of any help if you run to any issues.

Thanks!
