### ISSUE TITLE
SDK 2.0

### ISSUE THREAD

**Issue by aaronbach** [smartlook/cordova-smartlook#37]
Hi Smartlook, when do you plan to update the cordova plugin to work with Smartlook SDK 2.0? We are looking forward to disable Input masking. Is there a workaround at the moment?

Love the product

Cheers
Aaron

**Comment by c0mtru1se** [comment]
Hi!
I will be starting the work on the 2.x SDKs support in the coming days, ETA in the next few weeks.
Thanks for your patience!
