### ISSUE TITLE
Custom Navigation Event is not being detected on Ionic 

### ISSUE THREAD

**Issue by timonjagi** [smartlook/cordova-smartlook#54]
I'm implementing Smartlook on an Ionic v6 project using `this.smartlook.trackNavigationEvent` to track screen transitions, but when I define a new event on the dashboard, the events are not being detected.

I'm defining the event as a ''Visited Screen" event with `screen_name` being the name passed to `trackNavigationEvent` 

I'm assuming this is the correct way to do it since the documentation on [Recording Navigation](https://mobile.developer.smartlook.com/v1.0/docs/recording-navigation) says 
> The navigation event recorded by this method is indistinguishable from the auto-detected navigation events.

**Comment by c0mtru1se** [comment]
Hi!
Just fyi we have released today a brand new, ground-up rewritten [version 2.0 of this plugin](https://github.com/smartlook/cordova-smartlook/releases/tag/v2.0.0). It uses our new, also rewritten and long-term supported 2.x+ native SDKs. Everything, including the navigation tracking, is working better and more stable in those.

We have also pushed a [PR](https://github.com/danielsogl/awesome-cordova-plugins/pull/4510) to the `awesome-cordova-plugins` repository. Once the PR gets merged and released, you should be able to use both those plugins in your Ionic project (Capacitor is also fully supported and tested by us internally).
Please then kindly consult our [docs](https://mobile.developer.smartlook.com/reference/cordova-sdk-integration) to migrate to the v2.0 as there were some breaking changes in the API. I'll gladly be of any help if you run to any issues.

Thanks!
