### ISSUE TITLE
iOS app crashes before starting 

### ISSUE THREAD

**Issue by Dianatr23** [smartlook/cordova-smartlook#58]
<img width="531" alt="Screenshot 2023-03-06 at 15 28 52" src="https://user-images.githubusercontent.com/56507329/223123517-6ae8f47c-71d7-42d1-898f-e398235d1cac.png">

iOS app crashes before starting

**Comment by c0mtru1se** [comment]
Hi!
Can you please share more informations about the crash? What package version you used, in what type of project are you integrating it and perhaps the integration code?
Thanks.

**Comment by c0mtru1se** [comment]
Closing as non-responsive for now, please feel to reach out if you still face any issues.
Thank you!

**Comment by jake361361** [comment]
I've had the same issue.

Cordova Apache.

Xcode 14.3

Downgrading from smartlook 2.0.1 to 1.9.6 fixed the issue.
