### ISSUE TITLE
Deprecated API Usage

### ISSUE THREAD

**Issue by mival** [smartlook/cordova-smartlook#6]
In file https://github.com/smartlook/cordova-smartlook/blob/master/src/ios/SmartlookPlugin.m#L42 there is usage of UIWebView, which is deprecated.

Usually cordova plugins fix this using config variable for disabling UIWebView usage.

`ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.`

**Comment by maxymczech** [comment]
https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html

**Comment by pavel-kroh-smartlook** [comment]
Hi, thanks a lot for reminder and suggested solution. The latest Smartlook plugin release fixes the issue.
