### ISSUE TITLE
Duplicate class a.a found in modules

### ISSUE THREAD

**Issue by sanvisser** [smartlook/cordova-smartlook#76]
Hi! 
Since adding this plugin to my Ionic Capacitor Angular project I get the following error whilst running 'ionic cap run android'.

```
 > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
[capacitor]         > Duplicate class a.a found in modules jetified-smartlook-analytics-frame-capturer-2.2.0-runtime (com.smartlook.android:smartlook-analytics-frame-capturer:2.2.0) and jetified-tslocationmanager-3.4.5-runtime (com.transistorsoft:tslocationmanager:3.4.5)
```

It seems there might be some obfuscation going on in both libraries. Problem is that I can't just remove one of them, which seems to be the suggested solution most of the time, because they both serve different purposes. Using smartlook and our main location library.

I'm wondering if it's possible to fix this on the libraries end?

**Comment by c0mtru1se** [comment]
Hi there!
Thanks for reaching out.
This seems like an odd issue, as the `tslocationmanager`'s Android SDK might be missing a `proguard` rule preventing the conflicting obfuscation (e.g. `a.a.xxx`) and the jetifier picks it incorrectly.
I've just released a new version, `2.0.3` which attempts to fix this on our side, so please do try it out and let me know if it help.
Thank you!
