### ISSUE TITLE
[Android] Smartlook.start() freezes app functions for 2 seconds

### ISSUE THREAD

**Issue by wif70068** [smartlook/cordova-smartlook#81]
With Capacitor 5 on Android, executing Smartlook.start() causes certain native functions, such as native HTTP requests (e.g., via CapacitorHTTP) or the initialization of the OneSignal SDK, to freeze for 2 seconds.

During this time, logcat repeats the following for the entire 2 seconds:

`05-21 02:25:27.702   879   879 I vendor.qti.hardware.servicetracker@1.2-service: bindService is called for service : com.test.app/com.smartlook.android.job.worker.session.UploadSessionJob and for client system
05-21 02:25:27.702   879   879 I vendor.qti.hardware.servicetracker@1.2-service: total connections for service : com.test.app/com.smartlook.android.job.worker.session.UploadSessionJobare :1
05-21 02:25:27.702   879   879 I vendor.qti.hardware.servicetracker@1.2-service: total connections for client : systemare :24
05-21 02:25:27.706   879   879 I vendor.qti.hardware.servicetracker@1.2-service: unbindService is called for service : com.test.app/com.smartlook.android.job.worker.session.UploadSessionJob and for client system
05-21 02:25:27.721   879   879 I vendor.qti.hardware.servicetracker@1.2-service: bindService is called for service : com.test.app/com.smartlook.android.job.worker.session.UploadSessionJob and for client system
05-21 02:25:27.721   879   879 I vendor.qti.hardware.servicetracker@1.2-service: total connections for service : com.test.app/com.smartlook.android.job.worker.session.UploadSessionJobare :1
05-21 02:25:27.721   879   879 I vendor.qti.hardware.servicetracker@1.2-service: total connections for client : systemare :24
05-21 02:25:27.732   879   879 I vendor.qti.hardware.servicetracker@1.2-service: bindService is called for service : com.test.app/com.smartlook.android.job.worker.session.UploadSessionJob and for client system
05-21 02:25:27.732   879   879 I vendor.qti.hardware.servicetracker@1.2-service: total connections for service : com.test.app/com.smartlook.android.job.worker.session.UploadSessionJobare :1
05-21 02:25:27.733   879   879 I vendor.qti.hardware.servicetracker@1.2-service: total connections for client : systemare :24
05-21 02:25:27.738   879   879 I vendor.qti.hardware.servicetracker@1.2-service: unbindService is called for service : com.test.app/com.smartlook.android.job.worker.session.UploadSessionJob and for client system
`

This is observed as a 2-second delay on app startup because Smartlook is called at deviceready.

**Comment by c0mtru1se** [comment]
Hi! Thanks for the report and sorry for the delayed response, we've been busy with our Cisco integration stuff.
If this is still persisting for you, could you please kindly try to update to a newly release version, `2.0.6`? It uses our latest Android SDK with a lot of fixes & improvements.
Feel free to ping me here should the issue still persist and we can take it from there.
Thank you!

**Comment by wif70068** [comment]
doesn't seem to be an issue anymore with the new version
