### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by expcapitaldev** [smartlook/cordova-smartlook#9]
Tried to install plugin in our product (Cordova 8.1.2, ionic-angular 3.9.2) by 
**cordova plugin add https://github.com/smartlook/cordova-smartlook.git**
 and got fail:
_Failed to fetch plugin https://github.com/smartlook/cordova-smartlook.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module_

Could you help to solve it?

**Comment by maxymczech** [comment]
I've had same problem. Plugin is added in the NPM registry under `@danieleisenhardt/cordova-plugin-smartlook`

Try running `cordova plugin add @danieleisenhardt/cordova-plugin-smartlook`
